services:
  db:
    image: mysql:latest
    restart: always
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
      - tech-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: tech
    ports:
      - 3308:3306
    expose:
      - 3306

  server:
    depends_on:
      - db
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=tech
      - DB_USERNAME=root
      - DB_PASSWORD=123456
      - CLIENT_URL=http://localhost
      - CLIENT_PORT=80
    ports:
      - 5000:5000
    expose:
      - 5000

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 80:80
    expose:
      - 80
    environment:
      - PUBLIC_FOLDER=http://localhost
      - AXIOS_BASE_URL=http://localhost:5000/api/v1

volumes:
  tech-mysql-data:

    # docker compose -p tech up -d
