export const INIT_STATE_PRODUCTS = {
  dienthoai: {
    isFetch: false,
    category: null,
    countPage: null,
    currentPage: null,
    countProducts: null,
    payload: {},
  },
  tablet: {
    isFetch: false,
    category: null,
    countPage: null,
    currentPage: null,
    countProducts: null,
    payload: {},
  },
  laptop: {
    isFetch: false,
    category: null,
    countPage: null,
    currentPage: null,
    countProducts: null,
    payload: {},
  },
  tainghe: {
    isFetch: false,
    category: null,
    countPage: null,
    currentPage: null,
    countProducts: null,
    payload: {},
  },
  dongho: {
    isFetch: false,
    category: null,
    countPage: null,
    currentPage: null,
    countProducts: null,
    payload: {},
  },
  pc: {
    isFetch: false,
    category: null,
    countPage: null,
    currentPage: null,
    countProducts: null,
    payload: {},
  },
  sim: {
    isFetch: false,
    category: null,
    countPage: null,
    currentPage: null,
    countProducts: null,
    payload: {},
  },
  maygiat: {
    isFetch: false,
    category: null,
    countPage: null,
    currentPage: null,
    countProducts: null,
    payload: {},
  },
  tivi: {
    isFetch: false,
    category: null,
    countPage: null,
    currentPage: null,
    countProducts: null,
    payload: {},
  },
  tulanh: {
    isFetch: false,
    category: null,
    countPage: null,
    currentPage: null,
    countProducts: null,
    payload: {},
  },
  loa: {
    isFetch: false,
    category: null,
    countPage: null,
    currentPage: null,
    countProducts: null,
    payload: {},
  },
  quatdieuhoa: {
    isFetch: false,
    category: null,
    countPage: null,
    currentPage: null,
    countProducts: null,
    payload: {},
  },
};
