### api.http

### Not Found
POST http://localhost:4000/api/v1/notFound

### Register
POST http://localhost:4000/api/v1/auth/register
Content-Type: application/json

{
    "username": "havanduoc",
    "password": "123456"
}

### Login
POST http://localhost:4000/api/v1/auth/login
Content-Type: application/json

{
    "username": "havanduoc",
    "password": "123456"
}

