export const categories = [
  { id: 1, name: "Điện thoại", image: "dien-thoai.png", link: "/dien-thoai" },
  { id: 2, name: "Tablet", image: "tablet.png" },
  { id: 3, name: "Laptop", image: "laptop.png" },
  { id: 4, name: "Tai nghe", image: "tai-nghe.png" },
  { id: 5, name: "Đồng hồ", image: "dong-ho.png" },
  { id: 6, name: "PC", image: "pc.png" },
  { id: 7, name: "Sim", image: "sim.png" },
  { id: 8, name: "Tivi", image: "tivi.png" },
  { id: 9, name: "Tủ lạnh", image: "tu-lanh.png" },
  { id: 1, name: "Đồng hồ", image: "dong-ho.png" },
  { id: 1, name: "Đồng hồ", image: "dong-ho.png" },
  { id: 1, name: "Đồng hồ", image: "dong-ho.png" },
  { id: 1, name: "Đồng hồ", image: "dong-ho.png" },
  { id: 1, name: "Đồng hồ", image: "dong-ho.png" },
  { id: 1, name: "Đồng hồ", image: "dong-ho.png" },
  { id: 1, name: "Đồng hồ", image: "dong-ho.png" },
  { id: 1, name: "Đồng hồ", image: "dong-ho.png" },
  { id: 1, name: "Đồng hồ", image: "dong-ho.png" },
  { id: 1, name: "Đồng hồ", image: "dong-ho.png" },
  { id: 1, name: "Đồng hồ", image: "dong-ho.png" },
  { id: 1, name: "Đồng hồ", image: "dong-ho.png" },
  { id: 1, name: "Đồng hồ", image: "dong-ho.png" },
];
