export const categories = [
  { name: "Điện thoại", image: "dien-thoai.png" },
  { name: "Tablet", image: "tablet.png" },
  { name: "Laptop", image: "laptop.png" },
  { name: "Tai nghe", image: "tai-nghe.png" },
  { name: "Đồng hồ", image: "dong-ho.png" },
  { name: "PC", image: "pc.png" },
  { name: "Sim", image: "sim.png" },
  { name: "Đồng hồ", image: "dong-ho.png" },
  { name: "Đồng hồ", image: "dong-ho.png" },
  { name: "Đồng hồ", image: "dong-ho.png" },
  { name: "Đồng hồ", image: "dong-ho.png" },
  { name: "Đồng hồ", image: "dong-ho.png" },
  { name: "Đồng hồ", image: "dong-ho.png" },
  { name: "Đồng hồ", image: "dong-ho.png" },
  { name: "Đồng hồ", image: "dong-ho.png" },
  { name: "Đồng hồ", image: "dong-ho.png" },
  { name: "Đồng hồ", image: "dong-ho.png" },
  { name: "Đồng hồ", image: "dong-ho.png" },
  { name: "Đồng hồ", image: "dong-ho.png" },
  { name: "Đồng hồ", image: "dong-ho.png" },
  { name: "Đồng hồ", image: "dong-ho.png" },
  { name: "Đồng hồ", image: "dong-ho.png" },
];
